### ISSUE TITLE
Test VO A/R calculations

### ISSUE THREAD

**Issue by skanct** [ARGOeu/ARGO#1]
We have added support for VO A/R calculations in the Compute Engine. We need to test the following:

- [ ] Calculate A/R for a VO using the data we already have in HDFS
- [ ] Publish VO A/R through the WebAPI
- [ ] Present VO A/R on the WebUI

(24h) @pkoro

**Comment by pkoro** [comment]
Following our discussion on Skype Dev we can use the python script [here][l1] (see also [this reference][l2]) to generate VO feed xmls and then parse them through vo-sync component to get the topology we require. This would require that we install the lcg-infosites package on the sync node (it's a small package containing only the executable and its man page). 

The vo-sync executable outputs in text files the topology for a given VO. I have tested this with a couple of xml feeds and I believe the following changes need to be done:

1) Modify the output per VO. If we follow the multitenant approach this means the outputs of the script should be placed in a separate folder for example per VO. 
2) Fix the parsing of the xml feed. I noticed that the parsing is not correct. To be more exact from [this][l3] xml I got [this][l4] output text file, so there is a small bug somewhere within vo-sync
3) Allow for more than one VOs to be synced (i.e. via configuration file probably, allow ARGO user to define topology from which VOs to sync)

[l1]: https://github.com/kashif74/vo-feed/blob/master/vo-feed.py
[l2]: http://southgrid.blogspot.gr/2014/10/nagios-monitoring-for-non-lhc-vos.html
[l3]: http://fpaste.org/196948/14261456/raw/
[l4]: http://fpaste.org/196946/42614541/raw/
