### ISSUE TITLE
Update POEM UI

### ISSUE THREAD

**Issue by vrdel** [ARGOeu/ARGO#113]
- [x] https://github.com/ARGOeu/poem/issues/8
- [x] https://github.com/ARGOeu/poem/issues/7
- [x] https://github.com/ARGOeu/poem/issues/6

**Comment by vrdel** [comment]
https://github.com/ARGOeu/poem/issues/8

**Comment by skanct** [comment]
@vrdel is this still relevant?

**Comment by vrdel** [comment]
Yes. This is the new look: https://github.com/elky/django-flat-theme

**Comment by vrdel** [comment]
https://github.com/ARGOeu/poem/pull/30
