### ISSUE TITLE
Specification of the metric result schema

### ISSUE THREAD

**Issue by skanct** [ARGOeu/ARGO#115]

**Comment by eimamagi** [comment]
Messages sent from SAM Nagios instances consist of header and body. 

Header contains the following fields:
- sitename: SITENAME
- nagios_host: NAGIOS
- ROC: NGI_XX
- role: ngi|roc|project|vo
- destination: /topic/grid.probe.metricOutput.EGEE.ngi.SITENAME
Body contains the following fields:
- serviceURI: SERVICE_URI
- hostName: HOSTNAME
- serviceFlavour: SF
- serviceType: SF
- siteName: SITENAME
- metricStatus: OK|WARNING|UNKNOWN|CRITICAL
- metricName: MN
- summaryData: METRIC_OUTPUT
- detailsData: METRIC_DETAILS_OUTPUT
- gatheredAt: EXEC_LOCATION
- timestamp: TS
- nagiosName: MN_FULL
- role: ngi|roc|project|vo
- voName: VO
- voFqan: VO_FQAN

Example of body:
serviceURI: ce.irb.egi.cro-ngi.hr
hostName: ce.irb.egi.cro-ngi.hr
serviceFlavour: CREAM-CE
siteName: egee.irb.hr
metricStatus: OK
metricName: emi.cream.CREAMCE-DirectJobSubmit
summaryData: OK: DONE.
gatheredAt: mon.egi.cro-ngi.hr
timestamp: 2015-03-13T22:13:54Z
nagiosName: emi.cream.CREAMCE-DirectJobSubmit-ops
role: ngi
voName: ops
voFqan: ops
serviceType: CREAM-CE
detailsData: OK: DONE.\\nOK: DONE.\nEOT

**Comment by eimamagi** [comment]
Format for messages is based on the following specification:
 https://twiki.cern.ch/twiki/bin/view/LCG/GridMonitoringProbeSpecification
