### ISSUE TITLE
Publish ansible playbook for web api node

### ISSUE THREAD

**Issue by skanct** [ARGOeu/ARGO#120]
Support for:

- [x] Installation, configuration of web api (1h) @pkoro 
- [x] Installation, configuration of MongoDB (1h) @pkoro 
- [x] Documentation (1h) @pkoro 
- [x] Upgrade to version 3 of MongoDB (12h)  @dpavlos

**Comment by pkoro** [comment]
Christo, can you create an empty repo on github for this? The one under gitlab is named argo-prod-deploy but you may name this new one as you wish, 
Paschalis

**Comment by skanct** [comment]
@pkoro ready: argo-ansible

**Comment by pkoro** [comment]
Ok, I have placed a first (direct) commit under the new repo. It contains a play for 

1) adding necessary repo definitions on clean RHEL6 VM
2) adding certificate to the VM (required for API)
3) Installation and configuration of mongodb
4) Installation of our web api service.

**Comment by dpavlos** [comment]
The update of the mongo DB and the switch of the underlying storage engine will be performed manually. So I'm closing the related issue for now.
