### ISSUE TITLE
Enable VO feeds syncing via ar-sync components

### ISSUE THREAD

**Issue by pkoro** [ARGOeu/ARGO#121]
Following the discussion on #1 we should modify the vo-sync component. 

First, if all agree, we can use the python script [here][l1] (see also [this reference][l2]) to generate VO feed xmls and then parse them through vo-sync component to get the topology we require. This would require that we install the lcg-infosites package on the sync node (it's a small package containing only the executable and its man page). 

Furthermore, I believe the following changes need to be done:

1) Modify the output per VO. If we follow the multitenant approach this means the outputs of the script should be placed in a separate folder for example per VO. Ideally the vo-sync should write the group of groups and group of endpoints avro files under the EGI tenant in a folder indicating somehow the name of the VO, so at the end we should have `/var/lib/ar-sync/EGI/see/group_endpoints_YYYY_MM_DD.avro` and `/var/lib/ar-sync/EGI/see/group_groups_YYYY_MM_DD.avro`, ie for the see VO)
2) Fix the parsing of the xml feed. I noticed that the parsing is not correct. To be more exact from [this][l3] xml I got [this][l4] output text file, so there is a small bug somewhere within vo-sync
3) Allow for more than one VOs to be synced (i.e. via configuration file probably, allow ARGO user to define topology from which VOs to sync)

As a follow-up though, the vo-sync could be also merged within the topology-sync component, but this is up to @vrdel and @eimamagi to decide. 

[l1]: https://github.com/kashif74/vo-feed/blob/master/vo-feed.py
[l2]: http://southgrid.blogspot.gr/2014/10/nagios-monitoring-for-non-lhc-vos.html
[l3]: http://fpaste.org/196948/14261456/raw/
[l4]: http://fpaste.org/196946/42614541/raw/

**Comment by skanct** [comment]
I see both these components as different implementations of a topology connector. Of course by using the name topology-sync (for what actually is a gocdb connector) it implies that this is the only component that will be implementing the topology connector.

I think it is better to keep the vo sync separate from the topology sync and rename them to topology-vo-{sync,collector} and topology-gocdb-{sync,connector}.

**Comment by vrdel** [comment]
* Christos Kanellopoulos <notifications@github.com> [15-03-13 08:51]:
> I see both these components as different implementations of a topology
> connector. Of course by using the name topology-sync (for what
> actually is a gocdb connector) it implies that this is the only
> component that will be implementing the topology connector.
> 
> I think it is better to keep the vo sync separate from the topology
> sync and rename them to topology-vo-{sync,collector} and
> topology-gocdb-{sync,connector}.

So downtime-sync becomes downtime-gocdb-sync? 

How about a hepspec-sync? Should it remain as it is because we'are
not pulling it from GOCDB?

**Comment by skanct** [comment]
I agree with both of these. By the way, I have changed the name of the component to "-connectors" instead of "-sync". I think sync is not very accurate. Opinions?

**Comment by kaggis** [comment]
Indeed "-connectors" seem more explanatory than sync. What about "-feeds"?  Less letters, even more descriptive: feed= only reading information from a source
connector = reading / writing information to a source

**Comment by skanct** [comment]
+1

**Comment by vrdel** [comment]
I don't know, I leave that up to you. I would think of "connector" of
something that's is permanently tied to something else and "syncer"
something that occasionally settles down it's behaviour/data against
something else (what we do), so personally I would go with "sync".

**Comment by vrdel** [comment]
Hmm, feed. Ok, I find on a filesystem file called topology-gocdb-feed. Is it a provider or a reader? I find it slightly ambiguous.

**Comment by pkoro** [comment]
Hi, I am following this up a bit as a had some time during this week to check things. 

On the VO sync I have two comments I would like to discuss. First one is about tenants and how we place the files. Within the default configuration [this][t1] is the directory structure one gets. On the other hand, [this][t2] is what I would envision. @vrdel Can I make this change easily just by changing the configuration files or would it require further development?

The second comment is about the vo syncing capability itself. Currently one places -from what I understand- a URL pointing to an xml feed in the configuration. Could we use in conjunction to this component the [python script][t3] that was suggested also in the ticket? What do you think?

Can we discuss these comments tomorrow during our regular call?

Thanks,
Paschalis

[t1]: http://paste.fedoraproject.org/211673/84594142/
[t2]: http://fpaste.org/211717/42918644/
[t3]: https://github.com/kashif74/vo-feed/blob/master/vo-feed.py
