### ISSUE TITLE
Question on what prefilter reports as rejected messages

### ISSUE THREAD

**Issue by pkoro** [ARGOeu/ARGO#128]
A few moments ago I noticed the following thing:

When I call the prefilter for a given day (say the 15th) it returns the following message:

```
Rejected: 1010
```

When I inspect the number of records within the consumer and prefiltered files I see the following:

```
# avro cat ar-consumer_log_2015-04-15.avro | wc -l
456874  
# avro cat prefilter_2015_04_15.avro | wc -l
419785
```

The discrepancy is `456874-419785 = 37089 != 1010`

I am misunderstanding what the Rejected message says?

**Comment by vrdel** [comment]
I've planned to fix that while I'll be dealing with the logging of the connectors. Currently, prefilter-egi.py reports only the number of rejected messages based on the following criteria:
- metric in the message is not found in any fetched POEM profile
- service type in the message is not found in any fetched POEM profile

What is missing is the number of rejected messages coming from nagios boxes that are not registered for certain NGI.
