### ISSUE TITLE
Find SAM Nagios VO working instance

### ISSUE THREAD

**Issue by pkoro** [ARGOeu/ARGO#130]
It's suggested in the context of #1 that we also investigate consuming metric results from a valid Nagios VO box. Emir has volunteered to locate one such instance.

**Comment by eimamagi** [comment]
Lets go with gridpp, described here:
 http://southgrid.blogspot.com/2014/10/nagios-monitoring-for-non-lhc-vos.html

SAM VO instance is working and its properly registered in GOCDB. You can find results here:
 https://vo-nagios.physics.ox.ac.uk/nagios/

VO feed for gridpp is defined on the link above:
 http://www-pnp.physics.ox.ac.uk/~mohammad/gridpp.feed.xml

Results from this thing should be on topic:
 /topic/grid.probe.metricOutput.EGEE.vo 
so consumer should be configured to look there.

POEM profile should be fetched from the SAM VO instance:
 https://vo-nagios.physics.ox.ac.uk/poem/admin/poem/profile/
Seems TESTING is the one used for gridpp.

**Comment by pkoro** [comment]
Hi Emir, 

thanks for the detailed update. I have configured the consumer on the dev instance to read and write from the suggested topic but up to now I don't seem to be consuming messages from this particular instance. In case you have access on that box can you cross-check which is the topic the instance is using to relay messages? Or maybe we can ask the admins? 

Thank you again,
Paschalis

**Comment by eimamagi** [comment]
On 19.5.2015. 15:34, Paschalis Korosoglou wrote:
> Hi Emir,
>
> thanks for the detailed update. I have configured the consumer on the
> dev instance to read and write from the suggested topic but up to now I
> don't seem to be consuming messages from this particular instance. In
> case you have access on that box can you cross-check which is the topic
> the instance is using to relay messages? Or maybe we can ask the admins?
>

As far as I can see they are publishing something:
https://vo-nagios.physics.ox.ac.uk/nagios/html/pnp4nagios/index.php?host=vo-nagios.physics.ox.ac.uk&srv=org.egee.SendToMsg

Do you get anything with monitoring_host: vo-nagios.physics.ox.ac.uk?

**Comment by pkoro** [comment]
Yeap, I also noticed the specific probe is green but I am not sure which topic they publish to. I am not sure what's going on cause I can't see any results from vo-nagios.physics.ox.ac.uk yet (besides the regular results from opsmon regarding that host). 

I'll try to debug from the brokers side tomorrow. 

Thanks again, 
Paschalis

**Comment by eimamagi** [comment]
Daniel and me investigated this and found messages from this box. He will give you more info...

**Comment by pkoro** [comment]
Hi Emir, 

yes I also found messages using a custom consumer. The issue I am trying to figure out is why our consumer does not collect these even though I have added the topic in the configuration. Maybe Daniel is working on the same thing so we should pick it up on Skype chat. 

Best, 
Paschalis

**Comment by pkoro** [comment]
Hmm, I think I found the problem. `topics` is defined in two configuration files of the consumer, namely

`/etc/ar-consumer/ar-consumer.conf` and `/etc/ar-consumer/activemq-reader.conf`

Initially, I overlooked this and placed the additional set of topics in the first one. The consumer, however, seems to ignore that because when I placed it in the second file the consumer started receiveing the necessary messages.

**Comment by vrdel** [comment]
What necessary messages are you actually receiving? I haven't received any coming from vo-nagios.physics.ox.ac.uk monitoring instance on topic that Emir suggested.

Regarding consumer - yes, configuration and the whole code is a bit mess, that's why I refactored it.

**Comment by pkoro** [comment]
Well, I got a few lines. For example in the txt file:

```
2015-05-20T15:01:24ZUNDEFINEDvo-nagios.physics.ox.ac.ukorg.sam.SRM-DelSRMv2srmv2.ific.uv.esOKt2k.orgt2k.org
2015-05-20T15:01:24ZUNDEFINEDvo-nagios.physics.ox.ac.ukorg.sam.SRM-AllSRMv2srmv2.ific.uv.esOKt2k.orgt2k.org
2015-05-20T15:01:34ZUNDEFINEDvo-nagios.physics.ox.ac.ukorg.nordugrid.ARC-CE-ARISARC-CEt2arc01.physics.ox.ac.ukOK
2015-05-20T15:01:34ZUNDEFINEDvo-nagios.physics.ox.ac.ukorg.nordugrid.ARC-CE-submitARC-CEarc-ce05.gridpp.rl.ac.ukOKphenopheno
2015-05-20T15:01:34ZUNDEFINEDvo-nagios.physics.ox.ac.ukhr.srce.SRM2-CertLifetimeSRMv2svr018.gla.scotgrid.ac.ukOK
```

I can spot similar entries in the the avro encoded file as well. The configuration I have within `/etc/ar-consumer/activemq-reader.conf` is this:

```
topics = '/topic/grid.probe.metricOutput.EGEE.ngi.*;/topic/grid.probe.metricOutput.EGEE.roc.*;/topic/grid.probe.metricOutput.EGEE.opsmonitor.*;/topic/grid.probe.metricOutput.EGEE.project.*;/topic/grid.probe.metricOutput.EGEE.vo.*'
```
