### ISSUE TITLE
Move monitoring engine repositories to github

### ISSUE THREAD

**Issue by skanct** [ARGOeu/ARGO#158]
- [ ] ARGOeu/python-GridMon
- [ ] ARGOeu/perl-GridMon
- [ ] ARGOeu/argo-mon
- [ ] ARGOeu/glite-yaim-nagios
- [ ] ARGOeu/nagios-plugins-egi-security
- [ ] ARGOeu/nagios-plugins-globus
- [ ] ARGOeu/nagios-plugins-igtf
- [ ] ARGOeu/nagios-plugins-fedcloud
- [ ] ARGOeu/nagios-plugins-activemq
- [ ] ARGOeu/argo-nagios-egi
- [ ] ARGOeu/argo-nagios-tools
- [ ] ARGOeu/argo-msg-nagios

**Comment by skanct** [comment]
@eimamagi is this still relevant? Are there any repositories that wee need to move?

**Comment by eimamagi** [comment]
On 6/7/2016 17:48, Christos Kanellopoulos wrote:

> @eimamagi https://github.com/eimamagi is this still relevant? Are
> there any repositories that wee need to move?

nop, we can close it
