### ISSUE TITLE
Design of probe development framework

### ISSUE THREAD

**Issue by skanct** [ARGOeu/ARGO#159]
## Goals

- Support multiple authentication methods allowing to associate different authentication mechanism to each test;

## Discussion

There are probes, which require access to credentials in order to perform their tests. Right now probes can use a VOMS proxy that is available on the Monitoring Engine. The initial question is how can we provide support from probes that require different credentials? For example it could be the case that Probe A might required Credential A, while Probe B might require Credential B. Taking it one step further, Probe A might require Credential A for testing a specific instance of a Service Flavor and the same probe might require Credential B for testing another instance of the same Service Flavor.

https://docs.google.com/document/d/1qkVm5lNirsAc2Yan1WWA4-wPT9DUX26o-Ke15nqBpEI/edit#

**Comment by skanct** [comment]
@eimamagi, this is already supported, right? Can you please add a sort description and close the ticket (if this is the case)?

**Comment by themiszamani** [comment]
https://jira.argo.grnet.gr/browse/ARGO-537
