### ISSUE TITLE
Design of probe publishing and management service

### ISSUE THREAD

**Issue by skanct** [ARGOeu/ARGO#160]
The way we operate at the moment (beginning of EGI-Engage) is that Product Teams are responsible for developing their own probes. When the probes are ready, they are delivered to ARGO team, which packages the probes and creates a new release. Up to now the release of the probe package coincides with a new release of the Monitoring Engine (in the very recent past it used to be part of the Monitoring Engine Release). The probe release is deployed on the Monitoring Engine(s), but it is not used until POEM service is re-configured in order to include the Service Flavour (if it is a new type of product) and enable the metrics provided by the new probes for that Service Flavor.

How can we improve upon this? By separating the probes releases from the Monitoring Engine releases already it is possible to have more frequent release cycles for the probes. 

Idea: Can we extend the POEM service so that it becomes a registry for probes? 

How it could work:

1. Authorized users will be able to register new probes to the Probe publishing and management service. Each probe should have a name, a version, a description, a Service Flavor that it refers to, a repository URL and a status flag. 

2. Product teams should be able to register their own probes and set all the fields except from the status field. By default new probes are registered with status of “dev”. Available statuses are “dev”, “test”, “production”. The status can be changed by authorized users.

3. The NCG component on a Monitoring Engine can be extended to search the POEM probe registry and look for probe statuses. E.g. the Central Monitoring Engine, would be looking only for “production” probes. It would then download them from their repository using the name and version as identifiers. For certification purposes, a test monitoring engine might be looking for probes with “test” status and use download just those. 

What do we get with this? Basically we will be able to push new probes to production without any involvement from our side. It is the customers, who will decide what goes on production or not and we give them a simple tool to implement a verification process on top of our platform. 

https://docs.google.com/document/d/1qkVm5lNirsAc2Yan1WWA4-wPT9DUX26o-Ke15nqBpEI/edit#

**Comment by skanct** [comment]
@vrdel  can you update this ticket and add a link to the the design document?

**Comment by vrdel** [comment]
https://docs.google.com/document/d/1yret3FsoBcuVcxYRTkAyt7p5SCOygwUNXxfyQtSqMQ4/edit

**Comment by themiszamani** [comment]
https://jira.argo.grnet.gr/browse/ARGO-531
