### ISSUE TITLE
Probe development guidelines

### ISSUE THREAD

**Issue by skanct** [ARGOeu/ARGO#161]
Product teams should have clear guidelines on how they should be developing probes. In order to do so, we need first of all to have clear documentation located at one place, which will describe the basic steps a developed should take in order to start coding probes. There is some documentation at the CERN wiki, we should take that and build upon it. Along with the documentation we should provide also a skeleton template for bootstrapping the development of a new probe.

**Comment by themiszamani** [comment]
https://docs.google.com/document/d/1_x9qujX9mMS6wJysjJeJXJkSo9hl4TSrTCi7E4qVVsA/edit
