### ISSUE TITLE
APIv1 alpha specification

### ISSUE THREAD

**Issue by skanct** [ARGOeu/ARGO#165]
Evolution of the Messaging Service by providing a Restful HTTP API as a layer on top of the existing Message Broker Network. The introduction of a Restful Service layer on top of the Message Broker Network will give us the ability to implement also other much wanted features such as: access controls (AuthN/AuthZ), message accounting, implementation of QoS mechanisms

**Comment by themiszamani** [comment]
https://docs.google.com/document/d/1ANXVyOZL9bkCx_WXpYCPuWBLQ1Of72vW4Z3dvsgk5L0/edit
