### ISSUE TITLE
ARGO connectors should provide a help

### ISSUE THREAD

**Issue by pkoro** [ARGOeu/ARGO#169]
IMHO connectors should provide a `-h` or `--help` option on the command line. Please consider this as a helpful feature.

**Comment by vrdel** [comment]
Ok, I have implemented this but I thought that the whole point of putting connectors into /usr/libexec is that you don't execute them directly ([FHS, libexec](http://www.linuxbase.org/betaspecs/fhs/fhs/ch04s07.html)), ever.

So now you have for example:

``` 
% topology-gocdb-connector.py -h
usage: topology-gocdb-connector.py [-h]

Fetch wanted entities (ServiceGroups, Sites, Endpoints) from GOCDB for every
job listed in customer.conf and write them in an appropriate place

optional arguments:
  -h, --help  show this help message and exit
```

```
 % weights-gstat-connector.py -h
usage: weights-gstat-connector.py [-h]

Fetch weights information from Gstat provider for every job listed in
customer.conf

optional arguments:
  -h, --help  show this help message and exit
```
