### ISSUE TITLE
Wrong report in CSV/XML export

### ISSUE THREAD

**Issue by skanct** [ARGOeu/ARGO#188]
https://rt.egi.eu/rt/Ticket/Display.html?id=10545

> If I choose the NGI A/R report of whatever month, clicking either on the csv or xml buttons, it gives you always the report of the last three months
> 
> try for example http://argo.egi.eu/lavoisier/ngi_reports?month=2015-03

**Comment by cyril1er** [comment]
This is not a bug . The idea is to compare with the 2 previous months
