### ISSUE TITLE
Data retention for raw data

### ISSUE THREAD

**Issue by skanct** [ARGOeu/ARGO#76]
When we start a new status computation we copy the metric results of the current day to a temp folder in HDFS and we start the pig job. Every time a new computation later is run the data in that temp folder are being overwritten.

What we want to do is to archive in HDFS the data of the previous day. In the consumer we do need to keep the raw data for a longer period than two months.

- [x] Modify the compute engine to archive daily the raw data @kaggis 
- [x] Add data retention script in the consumer to drop data older than X time @lgjenero

**Comment by lgjenero** [comment]
Finished in f5b54c8717ff6acda128cada0875d38df5d35e3b

**Comment by kaggis** [comment]
The compute engine is configured to upload both the daily metric data and the daily sync data to the HDFS. 

Regarding the sync data which is actually a bunch of small files it would be highly un-optimized to keep them in HDFS. It's not uncommon to maintain temporarily small files in hdfs as scratch data but isn't efficient as a long-term storage. 

I could write a script to tar monthly sync data and drop them as archives in hdfs

**Comment by kaggis** [comment]
Compute engine is configured to upload daily clean metric data to HDFS
Compute engine also now contains a script to back-up monthly sync files to the HDFS

https://github.com/ARGOeu/ar-compute-engine/commit/52bbcfbce59539b5532440edb3563b46ba7eda63
