### ISSUE TITLE
Use the AVRO data serialisation framework for the communication between the sync components, the consumer and the compute engine

### ISSUE THREAD

**Issue by skanct** [ARGOeu/ARGO#85]
- [x] Defintion of the AVRO schema files
- [x] Support AVRO format in the consumer
- [x] Support AVRO format in the sync components
- [x] Support AVRO format in the prefiltering
- [x] Support AVRO format in the Compute Engine
- [x] Add also all the optional fields (AVRO) that are required for the computation

**Comment by kaggis** [comment]
Implemented also with the conclusion of the issue #93, Transfer of avro files in hdfs implemented with mechanisms in https://github.com/ARGOeu/ar-compute-engine/commit/79bb53488587f0ed2d6a32ef12149ecaf655e889 and https://github.com/ARGOeu/ar-compute-engine/commit/79bb53488587f0ed2d6a32ef12149ecaf655e889
