### ISSUE TITLE
Support for custom hierarchical grouping of entities

### ISSUE THREAD

**Issue by skanct** [ARGOeu/ARGO#87]
- [x] Defintion of the AVRO schema for hierarchical grouping of entities 
- [x] Support hierarchical grouping of entities in the sync components
- [x] Support hierarchical grouping of entities in the prefiltering
- [x] Support hierarchical grouping of entities in the Compute Engine

**Comment by kaggis** [comment]
Implemented in the latest ar-compute engine commits
