### ISSUE TITLE
Improve the logging in the compute engine

### ISSUE THREAD

**Issue by skanct** [ARGOeu/ARGO#88]
We have logging from the std out of the cron jobs. We want to enable central logging in syslog.

- [x] Use syslog for central logging in the init scripts  (6) @kaggis 
- [x] Use syslog  logging in the various hadoop components (8) @pkoro 
- [x] Debug level logging for the CE.
   - [x] Sync classes (16) @dfolias 
   - [x] MyUDFs (16) @dpavlos
   - [x] Data model (8) @kaggis

**Comment by kaggis** [comment]
Began testing 
- Mechanisms as pigLogger for more expressive custom console messages during computation script executions.
- The use of a remote logger inside ar-compute engine java classes, because the use of a classic logger doesn't cut it ... log messages are unpredictably being distributed to the various hadoop nodes during jobs
- The use of a simple datastore to keep track of each job (when started, when completed, status of completion)

I'll mark it as in-progress, is it possible to move it to the January sprint?

**Comment by dfolias** [comment]
Overview of the ar-compute-engine code is in progress so as to explicitly locate/define where/how new code should be implemented.

**Comment by pkoro** [comment]
I have also been looking into this a bit. Within our code I found this [comment][c1]. Within that particular piece of code (which is not used in the latest release to my understanding) we use the java.util.logging.Logger utility class and as the comment indicates this type of logging is not working properly in the hadoop cluster (distributed) case. 

I am not very sure but maybe we can use [PPNL][c2] in combination with [this][c3] to get what we want out of Pig/Hadoop. Again, maybe this approach is a bit overkill, we should discuss. I found a good implementation/example of this combination [here][c4]. 

I will also look a bit into pigLogger that Kostas has suggested. Maybe it's the best approach forward at this point. 

One more point to raise is that pig Latin does not allow for conditionals in the usual way. It nonetheless supports some helpful [operations][c5] and we may want to keep this in our mind for the future. 

 
[c1]: https://github.com/ARGOeu/ar-compute-engine/blob/master/status-computation/java/src/main/java/myudf/AddTopology.java#L86
[c2]: http://svn.apache.org/repos/asf/pig/trunk/src/org/apache/pig/tools/pigstats/PigProgressNotificationListener.java
[c3]: http://commons.apache.org/proper/commons-logging/guide.html
[c4]: https://github.com/twitter/ambrose/blob/master/pig/src/main/java/com/twitter/ambrose/pig/AmbrosePigProgressNotificationListener.java
[c5]: http://pig.apache.org/docs/r0.11.1/test.html#diagnostic-ops

**Comment by kaggis** [comment]
In the pull request:
https://github.com/ARGOeu/ar-compute-engine/pull/69

- Add logging options to global cfg
- Add logging support to upload metric script.

- [To be done]: Add same logging support to the rest of the scripts

Notes: 
Logging mechanism is being initialized two handlers: one for using the console stream and one for using a file stream (/var/log/...). All print statements have been replaced with calls to the logger to write messages. With each one call, logger prints to the console and at the same time writes to the log file. Logger is set to always display up to INFO messages to the console. 

At the ar-compute-engine.conf file there is a new section [logging] with two parameters (log_file, log_level). By default log_level is set to DEBUG and it's used by logger when writing to the /var/log/...

**Comment by skanct** [comment]
I found the following web page describing the use of syslog in hadoop:

 http://lzone.de/Configure%20Hadoop%20to%20use%20Syslog%20on%20Ubuntu

Have a look

**Comment by kaggis** [comment]
All subtasks have been implemented and merged
