### ISSUE TITLE
ARGO Documentation

### ISSUE THREAD

**Issue by skanct** [ARGOeu/ARGO#89]

**Comment by pkoro** [comment]
Some assignements I would suggest:

- [ ] [installation documentation][t1] @pkoro
- [ ] [sync components configuration][t2] @lgjenero 
- [ ] [consumer service configuration][t3] @lgjenero 
- [ ] [compute engine configuration][t4] @kaggis 
- [ ] [web ui configuration][t5] @cyril1er 

[t1]: https://github.com/ARGOeu/argodoc/blob/master/content/guides/installation.md
[t2]: https://github.com/ARGOeu/argodoc/blob/master/content/guides/sync.md
[t3]: https://github.com/ARGOeu/argodoc/blob/master/content/guides/consumer.md
[t4]: https://github.com/ARGOeu/argodoc/blob/master/content/guides/compute.md
[t5]: https://github.com/ARGOeu/argodoc/blob/master/content/guides/webui.md

**Comment by pkoro** [comment]
A first preliminary edition is available on http://argoeu.github.io/ . Docs should go into https://github.com/ARGOeu/argoeu.github.io/tree/master/guides

**Comment by pkoro** [comment]
Just an update on this ticket. There are two PRs open one on compute engine configuration and one on argo-connectors. We are still missing documentation for the consumer component. I think it's at this point the only thing missing.

**Comment by vrdel** [comment]
Yes. Currenly, I'm refactoring the consumer (configs, remove plaintext writer, renaming components) and afterward I will write a guide for it.
