### ISSUE TITLE
Consumer does not kill connections after new ones are established

### ISSUE THREAD

**Issue by pkoro** [ARGOeu/ARGO#92]
Following our earlier discussion today the issue with the duplicated messages may have to do with how ar-consumer handles disconnects. I am assigning the ticket to Luko for further investigation.

**Comment by lgjenero** [comment]
Fixed with latest updates.
Needs testing.

**Comment by lgjenero** [comment]
fixed in:
https://github.com/lgjenero/ar-consumer/commit/2a93e353770c44ca9a94e457ef72fd2f52be73ad
